name: Convert and Commit

on: push

jobs:
    convert-and-commit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.PAT }} # Personal Access Token
                  ref: ${{ github.head_ref }} # Reference (branch/tag) for checkout
                  fetch-depth: 0 # Fetch entire commit history

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

            - name: Run conversion scripts
              run: |
                  bash scripts/convert_all.sh  # Run conversion script

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "Automated conversion of files [skip ci]" # Commit message with skip CI tag
                  commit_user_name: "github-actions[bot]"
                  commit_user_email: "github-actions[bot]@users.noreply.github.com"
                  commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
                  branch: ${{ github.head_ref }} # Branch to commit changes
